
<section>
    <div class='container-fluid'>
        <div>
            <img class='img-responsive' src="img/quieto.png" width='150px' id='imgAvatar'>
        </div>

        <br>

        <div class='row'>
            
            <div id='conteudo'  class='col-sm-12' style='color: rgba(4, 143, 14, 0.8); font-size: 20px;'>
                
                <p>[Copyright 2023] Profile Information...</p>
                <br>
                <p  id='txt1' name='paragrafos' style='display: block' class='line piscar' data-texto='txt1' data-parte='' data-lang=''></p>
                <p  id='txt2' name='paragrafos' style='display: none' data-texto='txt2'></p>
                <p  id='txt3' name='paragrafos' style='display: none' data-texto='txt3'></p>

                <div class="p-3 row" id='btnFooter' style="background-color: rgba(0, 0, 0, 0.2);">
                            
            </div>
        </div>
    </div>
</section>
